# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6be5a4759bff8365939be331163bcc51ae029d004a12c5ee34b7ab79c04ea5c4035da7b0bc9f053bb3f4cac99982ccc72d9956f88c01417d90c857609cbce775

test:
  secret_key_base: 6c41a0796262ba62188edc967a1ad9b425b73e3b3a6319d4d45c8aef431cc83634691e4ec36ca5cd5edc9258466527081fd6d7143b3dc55965499e9c4c33085c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
